### ISSUE TITLE
需要能够获取 Token 的过期时间

### ISSUE THREAD

**Issue by chechaoyang** [linjunpop/weixin_js_sdk#2]
一般情况下，我们获取到 token，在它的有效期内可以重复使用。因此，我们需要记录每个 token 的过期时间，以便 token 过期时再次请求微信接口获取一个新的 token。

这种做法在一些请求次数限制很少的接口中十分必要，比如 jsapi_ticket，在测试中发现，只要很少的调用就回返回错误：

```
WeixinJsSDK::Errors::InvalidRequest (
        Code: 45009
        Message: reach max api daily quota limit

        Please read the doc: http://mp.weixin.qq.com/wiki/17/fa4e1434e57290788bde25603fa2fcbd.html
)
```

官方说明见文档：
http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html#.E9.99.84.E5.BD.951-JS-SDK.E4.BD.BF.E7.94.A8.E6.9D.83.E9.99.90.E7.AD.BE.E5.90.8D.E7.AE.97.E6.B3.95

**Comment by linjunpop** [comment]
已发布 v0.0.2
