### ISSUE TITLE
考虑把 access_token 和 ticket 放入 Cache 吗？

### ISSUE THREAD

**Issue by ghost** [linjunpop/weixin_js_sdk#5]
使用中在外部把 access_token 和 ticket 放入 Rails Cache 中，根据 expires_in 自动过期。不过，如果能在 Gem 内部实现，我觉得更好。

**Comment by linjunpop** [comment]
我觉得 cache 的部分根据使用场景的不同，有不同的用法，如果需要共用，你可以再自己实现一个 gem，加上 cache :beers: 

可以参照 demo https://github.com/linjunpop/weixin-js-sdk-sample/blob/master/app.rb
